var applicantData = {
    staffName: '',
    dateCompleted: '',
    firstname: '',
    lastname: '',
    dob: '',
    gender: '',
    nationality: '',
    mobileNo: '',
    phoneNo: '',
    email: '',
    addressLineOne: '',
    addressLineTwo: '',
    town: '',
    region: '',
    postcode: '',
    courseSelect:  { selectedCource: '', fulltimeorPartTime: ''},
    gcseGrades: { subject: '', gradeAchieved: ''},
    otherGrades: { subject: '', gradeAchieved: ''},
    levelThreeGrades: { qualification: '', subject: '', grade: '', yearAchieved: ''},
    schoolOrCollageName: ''
};